# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ko', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('department_ko', models.CharField(max_length=100)),
                ('department_en', models.CharField(max_length=100)),
                ('position_ko', models.CharField(max_length=100)),
                ('position_en', models.CharField(max_length=100)),
                ('person_type', models.CharField(choices=[('F', 'Faculty'), ('C', 'Contributor')], max_length=1)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
